### ISSUE TITLE
Serial API: return all info in JSON object

### ISSUE THREAD

**Issue by murkle** [Gissio/radpro#10]
It would be quite handy (and more robust for knowing which bit of info has been returned) if there was an API call like **GET allInfo** which could return something like

`{"tubePulseCount": 35, "deviceId": "Bosean FS-1000;Rad Pro 2.0beta9;1414549528", "deviceTemperature": 16.6, "deviceTime": 1699699817, "tubeTime": 446, "tubeRate": 4.518, "tubeDutyCycle": 0.500,"tubeConversionFactor": 68.400,"tubeDeadTime": 0.0006695,"tubeDeadTimeCompensation": 0.0000000,"entropy": "8f46"}`
 
also "deviceId": "Bosean FS-1000;Rad Pro 2.0beta9;1414549528" could be split as eg

`"deviceName": "Bosean FS-1000", deviceSoftware:"Rad Pro 2.0beta9", "deviceId":"414549528`

**Comment by Gissio** [comment]
I try to keep the API as simple as possible. I don't think doing what you suggest is a good idea.
