### ISSUE TITLE
FNIRSI GC-01 (CA32F0502L3): Support

### ISSUE THREAD

**Issue by Zendium0** [Gissio/radpro#103]
Hi there!
I ordered a FNIRSI GC-01 off Aliexpress to experiment with your fantastic firmware.
Upon teardown I ran into a completely different hardware to that described here on Githud.
No battery, no visible piezo and an unmarked IC and screen ribbon.

Am I completely out of luck?
Any idea as to which electronics it is and compatibility?

Thank you!!
Federico 

![20240617_202155](https://github.com/Gissio/radpro/assets/54669252/6d8a1cec-0bb7-4c5c-bf7b-f07d5519d00b)

**Comment by Gissio** [comment]
Please read #48.

**Comment by Zendium0** [comment]
Thanks for the quick reply. 
I did have a suspension that my was the funky unit.
Difficult to spot the good units, FNIRSI doesn't seem to have an official store on Amazon.

Should you be interested I have found a data sheet for the chip version.

Thanks again!!
[CA32F0156系列MCU_产品介绍.pdf](https://github.com/user-attachments/files/15876983/CA32F0156.MCU_.pdf)
