### ISSUE TITLE
Reverting back to the original firmware

### ISSUE THREAD

**Issue by ullix** [Gissio/radpro#123]
Is it possible, to revert a FNIRSI GC-01 device with Radpro back to the original, factory, firmware? How?

**Comment by gc01noob** [comment]
if you download the whole repo and look for the folder called docs, inside there is a GC01 folder then a firmware folder. you'll find the stock .bin for your CPU in there
using any Linux GUI drag the 1.6 version over to the device BOOTLOADER drive window, leave the window open, then drag it over again and overwrite and you'll be back to stock 1.6-2

**Comment by gc01noob** [comment]
ps. you can mess about with Windows if you like but you'll end up pulling your hair out. even Live booting Ubuntu from a USB drive is simpler.
