### ISSUE TITLE
Unable to set the date/time

### ISSUE THREAD

**Issue by morfikov** [Gissio/radpro#128]
I just found this project and gave it a try, because my GC-01 just stopped working for unknown reason (when turned on it just make a noisy beeep sound, there's no way to turn it off). 

I flashed the radpro firmware and my GC-01 backed to life.

The problem I see with the radpro firmware is that I wasn't able to set the time/date. When I try to do so, the device reboots and when it's booted again, the time/date is not set.

MCU: CH32F103R8T6

**Comment by dc1rdb** [comment]
You might want to check the button battery for the real time clock. Looks like it is depleted...

**Comment by morfikov** [comment]
Yes it was, but yesterday I replaced it with a brand new one.

**Comment by Gissio** [comment]
Since you report your device is defective, I doubt the issue is related to Rad Pro.
