### ISSUE TITLE
YT-203B: Temperature

### ISSUE THREAD

**Issue by mulcmu** [Gissio/radpro#13]
I flashed [2.0beta11](https://github.com/Gissio/radpro/releases/tag/2.0beta11) onto two YT-203B with GD32F150 MCUs.  The device temperature shown on the statistics screen for both units fluctuates between 320 to 323 °C at room temperate (about 19°C).

**Comment by Gissio** [comment]
That seems like a hot issue! Will be fixed in the following beta. Please watch the project so you get notified when there are news.

**Comment by Gissio** [comment]
I have just released 2.0beta14. Could you check if it works now?

**Comment by mulcmu** [comment]
I just tried beta16 on one of these.  Better but still running a bit high.  Reading is around 30.0°C or so and pretty noisy.  Ambient was about 19°C again.

**Comment by Gissio** [comment]
Thanks for the report. I'm glad it works now. Remember, the temperature is device temperature (measured at the MCU), not ambient temperature, so 30.0°C seems allright!

I'll keep this issue open as I'm still planning some changes in the coming days.

**Comment by Gissio** [comment]
I forgot to mention. There are new Contrast and Brightness settings. Do they work? Did contrast improve the display?

**Comment by mulcmu** [comment]
Contrast and brightness both worked well.  Setting 3 on the contrast was perfect for test unit.  Level 8 was solid black which would make it difficult to adjust if it was errantly set that high and menu was exited.  

There might be a regression with the battery indicator.  It was showing empty on beta16, cells measured 2.85 volts on DMM while installed.

**Comment by Gissio** [comment]
I have just released [2.0beta17](https://github.com/Gissio/radpro/releases). Can you see if the battery indicator works now?

**Comment by Gissio** [comment]
Repeat of https://github.com/Gissio/radpro/issues/21.

Should be fixed in beta19.

**Comment by mulcmu** [comment]
[2.0beta19](https://github.com/Gissio/radpro/releases/tag/2.0beta19) tested and working great

**Comment by Gissio** [comment]
I'm glad it works now!
