### ISSUE TITLE
FNIRSI GC-01: Inconsistent radiation readings

### ISSUE THREAD

**Issue by morfikov** [Gissio/radpro#130]
I've been testing the firmware for a day, and something is wrong. When the device is booted, everything seems to be good. But after a minute or two, the readings raise from 0,2uSv/h to 100-200uSv/h. And no, I'm not in the vicinity of Chernobyl. :] When I covered the left side of the GC-01 counter with my hand, the readings dropped to normal. When I uncovered it, the device seemed to work fine for a while, and after a minute or two it started to show 100-200uSv/h again. Does anyone have a similar issue?

**Comment by jasperweiss** [comment]
A picture of the inside might make it easier to tell what's going on. What tube does it have? If the seller replaced it with a cheaper one, which is what most sellers do, unless you bought it from F-NIRSI directly, they might not have bothered to change the voltage level to something appropriate for that tube. You need to set the proper conversion factor as well (but it's not going to solve the spiking).

**Comment by gc01noob** [comment]
the first GC01 I purchased did similar, it showed readings that would mean that my entire town would be cooked within minutes (over 300 uSv/h). i returned it.
second one works perfectly.
If it did work before the firmware upgrade check that:
1. you have selected the correct tube in the settings
2. you use the correct firmware for your CPU - try a reflash back to 1.6 and back again
3. if above is all ok, make/buy a high voltage probe and check the tube voltage - if it's too high you can either solder on a reducing resistor or create a new profile to reduce the voltage - there's a recent discussion on how to do this.

**Comment by morfikov** [comment]
It's directly from F-NIRSI and with the stock firmware it was working well for over a year. With radpro it was also working well for a few hours, but suddenly it started to acct weird.  

Here are the photo: https://imgur.com/a/IthGvlL

**Comment by dc1rdb** [comment]
Stock firmware at https://github.com/Gissio/radpro/tree/main/docs/devices/FNIRSI%20GC-01/firmware

Your tube voltage is way too low. Should be between 360 and 440 Volts.

**Comment by morfikov** [comment]
The stock firmware acts the same. So apparently something is wrong with the device.

**Comment by Gissio** [comment]
Since you report the original firmware presents the same issue, I doubt the issue is related to Rad Pro.
