### ISSUE TITLE
BR-9B: Support

### ISSUE THREAD

**Issue by sunsmoke** [Gissio/radpro#132]
Unknown manufacturer, model BR-9B
cpu is: https://www.stcmicro.com/stc/stc8a8k64d4.html
other hardware:
color lcd
5 hardware switches
speaker/clicker
microusb port(power only?)
powered by 3x AA
![20240818_233952](https://github.com/user-attachments/assets/9adf1716-64fd-4f16-8d24-22e383872f42)

![20240818_233941](https://github.com/user-attachments/assets/209c6018-488b-43e0-865c-e52a86fe99e1)

**Comment by Gissio** [comment]
I don't own a BR-9B nor have I ever worked with STC8A8K microcontrollers, so I can't support it.

But I can give you some hints as to what would need to be done (general hints, not support):

* Follow the traces from the microprocessor to the board's devices (keyboard, display, battery, etc) and see what port connects to what device. A multimeter might help.
* The 4-pin header is most likely an SWD connector. If that is the case, get an ST-LINK/V2 adapter and attempt to download the firmware through it. Then use some disassembly tool to disassemble the firmware, and see how the code accesses the STC8A8K internal devices (input/output ports, timers, ADCs, etc).
* Follow the steps in https://github.com/Gissio/radpro/blob/main/docs/developers.md and customize the code for the STC8A8K/BR-9B.

This should make a nice project...
