### ISSUE TITLE
FNIRSI GC-01: Push data to gmcmap

### ISSUE THREAD

**Issue by digimacska17** [Gissio/radpro#138]
![image](https://github.com/user-attachments/assets/5af01f9c-be2f-4f84-b0f7-42598a376dcc)
I want to upload live data to https://gmcmap.com/ using GeigerLog V1.4.1 but the CPM is grayed out and don't know why. and not found any device mapping for RadPro to show the CPM data, only CPS. Any help would be appreciated. 
Tube: J321,
![image](https://github.com/user-attachments/assets/32783d3b-b481-4311-a444-0c4946ab3925)
![image](https://github.com/user-attachments/assets/286804c7-726c-4a26-a3e9-5bd154153283)

**Comment by Gissio** [comment]
As the read-me mentions, this is not an issue with Rad Pro but a request for help using GeigerLog. I suggest you ask for help in the GeigerLog forum!
