### ISSUE TITLE
FS2011 (GD32F150C8): Bug with Rad Pro 2.0.2

### ISSUE THREAD

**Issue by wim04** [Gissio/radpro#142]
version 2.0.2: FS2011 does not start up.
CPU: GD32 F 150 C8.
Flached with STLINK. Flach and verification ok.
Back to v2.0 and the FS2011 starts up.

**Comment by Gissio** [comment]
Thanks for the report! I'll take a look at this once I find the time.

**Comment by wim04** [comment]
The good news: version 201 and 202 starts up. There was a break in the power cable.
But neither of these versions shows any data. Menu and backlight is working.
Only version 2.0 works for me.

**Comment by Gissio** [comment]
Could you please make a video showcasing the error and upload it here? It would be tremendously useful.

**Comment by Dsl71** [comment]
Hi, I have 2.0.2 running fine on mine (same CPU, SBM20-U mod), FYI.

**Comment by Gissio** [comment]
Thanks for the report.

Closing this issue, as its nature seems more specific than general.

**Comment by wim04** [comment]
Hi Gissio,

Sorry for the late reply!

There were 3 problems after flashing to version 2.02

- Brightness set to minimum
- Contrast set to minimum, When Contrast is set to minimum, nothing is readable on the screen
- HV profile was Custom instead of Default, result, no data on screen


Solution Contrast:
Turn on device
Push menu/ok
7x Down ( = Display)
menu/ok
1x Down  (= Contrast)
menu/ok
4x Down (Contrast level 5)
menu/ok
3x  >

2- No data on Display
Cause:
HV profile was Custom, result: no data on screen
Solution Change HV profile to Factory default
Tube J305

After that, version is ok and i can read the screen.

Greetings,
Wim

________________________________
Van: Gissio ***@***.***>
Verzonden: dinsdag 8 oktober 2024 18:39
Aan: Gissio/radpro ***@***.***>
CC: wim04 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Gissio/radpro] FS2011 (GD32F150C8): Bug with Rad Pro 2.0.2 (Issue #142)


Thanks for the report.

Closing this issue, as its nature seems more specific than general.

**Comment by Gissio** [comment]
Most likely this happened because you flashed the 2.0.2 upgrade on top of the 2.0 release.

Let me point to the 2.0.2 installation instructions: https://github.com/Gissio/radpro/releases/tag/2.0.2
