### ISSUE TITLE
Different tube 

### ISSUE THREAD

**Issue by J30789** [Gissio/radpro#144]
Hello I have the FNIRSI GC-01. Opening it up I have a different tube to the ones you listed. On the tube (pictured) it’s a GM4011H24.05 on the board you can see it says J613 but thought I check before I do anything else. The MCU is APM32F103RBT6 and the screen ribbon is ENH-TV0240b026

thanks in advance 
![IMG_1252](https://github.com/user-attachments/assets/b5691094-40d6-438d-b423-901f71f8a3e8)
![IMG_1251](https://github.com/user-attachments/assets/1c49a7c5-16e0-4a21-96fc-e0bb66b63c25)
![IMG_1250](https://github.com/user-attachments/assets/940a9611-0908-4061-9e14-57744813be4c)

**Comment by jonwhite227** [comment]
It's an M4011 made in May 2024. It's equivalent to the J321, so the correct tube for the GC-01, and far better than the J613. Nothing to worry about.

**Comment by J30789** [comment]
Love it! Thank you!
