### ISSUE TITLE
Firmaware file names confusion

### ISSUE THREAD

**Issue by mryndzionek** [Gissio/radpro#15]
The instructions mention files named like `radpro-fs2011-\[MCU\]-install-x.y.z.bin`, but the releases only have one file - `radpro-fs2011-1.3.0-install.bin`.

**Comment by Gissio** [comment]
Rad Pro 1.3 only supports FS2011-STM32F051. Rad Pro 2.0 also supports FS2011-GD32F150 and FS2011-GD32F103. The next release will have correctly named release files.
