### ISSUE TITLE
Different FS2011

### ISSUE THREAD

**Issue by mjwaxios** [Gissio/radpro#2]
Just received a FS2011 from amazon (6/27) and the board revision is the same as your picture, Z27809 but the CPU different:
GD32F150
C8T6
CEHH213
AJ2151
GigaDevice
       ARM

After programming, no display, no sounds, buttons don't seem to do anything.  Have not had time to recompile for the different processor yet.

Pictures to follow later...

**Comment by Gissio** [comment]
I am minutes away of publish a release that fixes this. Hang tight!

**Comment by mjwaxios** [comment]
Fantastic work.  Works like a champ.   Thanks.

**Comment by Gissio** [comment]
I have just uploaded the official 1.2.2 release. Hope you enjoy it!

**Comment by pixitha** [comment]
![IMG_4879](https://github.com/Gissio/radpro/assets/503771/8f51a1a2-efaf-49c1-8518-043d177338b1)

I have this same CPU type on mine, adding a picture in case you want to add it to the install doc. 1.2.2 works on this CPU perfectly.

**Comment by Gissio** [comment]
Nice! Thanks for posting.

That seems to be an M4011 tube. BTW, some of those are photosensitive, so you might want to expose your tube to sunlight and see if the radiation level goes up. If it does, wrap your tube in black plastic.

**Comment by pixitha** [comment]
Would it be beneficial to upload the orig backup firmware somewhere for others?

**Comment by Gissio** [comment]
From a legal point of view, I don't think that is a good idea.

BTW, did you get a private email?

**Comment by mjwaxios** [comment]
So my first backup failed (my problem) but I got a second one and pulled the firmware for it.  It would be nice to have a recovery file.  Do you have a copy of it  or do you need a copy (which I now have and tested)?


  *   Michael

________________________________

**Comment by Gissio** [comment]
I have just released Rad Pro 1.3.0 which adds support for the J305 tube.

**Comment by Gissio** [comment]
Rad Pro 2.0 Beta 11 is out!

https://github.com/Gissio/radpro/releases
