### ISSUE TITLE
Pudibei NR series (750, 850, 950) radiation monitor support

### ISSUE THREAD

**Issue by catgirl2137** [Gissio/radpro#23]
Hello
Your RadPro software mentions that it should support a NR-950 geiger counter.
Does it extend to other NR series devices? 
I'm most interested about NR-750 radiation monitor, as this is the one I planned on reprogramming.
This model uses a MSP430F147 microcontroller.
If the software is compatible, will I be able to use an ST-link for programming, like with FS-2011?
Finally, could You help me with locating reprogramming pins on the board, if I provide detailed photos of it?
Thank you, and wish you luck with this project!

**Comment by Gissio** [comment]
Thanks for pointing out an error. Indeed, Rad Pro does not support the NR series devices.

Let me also point to this issue, which explains why: https://github.com/Gissio/radpro/issues/5
