### ISSUE TITLE
FNIRSI GC-01: Turns on in HOLD mode

### ISSUE THREAD

**Issue by martin-machacek** [Gissio/radpro#25]
Everytime I turn the device on, it is in the Hold mode of Instantaneous screen. It does not matter if I previously turned it off in Hold mode or not. While turning it on, I release the center OK key as soon as the LED turns off and Rad Pro splashscreen appears.

**Comment by martin-machacek** [comment]
I may be holding the key for too long. If I release the key sooner, it still turns on, but not in Hold mode.

**Comment by Gissio** [comment]
I'm glad you could install Rad Pro successfully on your device!

Regarding the issue, this can be fixed! Thanks for the report.

**Comment by Tig3rch3n** [comment]
Just confirmed the issue.
If you hold Power just 1 Sec, Instantaneous is NOT on Hold
If you hold Power for >2 Sec it starts on Hold

**Comment by Gissio** [comment]
Beta20 should fix this. Let me know.

**Comment by martin-machacek** [comment]
I can confirm that it is fixed 👍

**Comment by Gissio** [comment]
Nice!
