### ISSUE TITLE
FNIRSI GC-01: Wrong device temperature statistics

### ISSUE THREAD

**Issue by Alter0ne** [Gissio/radpro#28]
Hello!
I have the device with ch32f103 processor. It shows the incorrect temperature: 9 °C when the environment is 28 °C.
[Photos](https://imgur.com/a/HX86Gs4)
Also my device resets the current date and time after rebooting. But the time zone is saved correctly. Perhaps it's my battery problem?

**Comment by Gissio** [comment]
Regarding the real-time clock. The date and time should work correctly. If it doesn't, check the button battery's voltage (it should be a CR1220). It should be around 3 V. If it doesn't, replace it!

And the temperature discrepancy is expected. STM32F103 and compatible microprocessors are not temperature calibrated in the factory. This means there can be a variation of up to ± 20 °C from the actual value, because the temperature sensor of different production batches can be phyiscally different.

To fix this, there should be a setting to calibrate this. That's actually a question I have been asking mytself. And this question goes to everyone who reads this. Does it make sense to show uncalibrated temperature? Should there be settings to fix this? In order to keep things simple, I think it would be best to not show temperature at all (if it's wrong, it makes no sense as it confuses more than helping).

**Comment by martin-machacek** [comment]
My device shows the temperature 13 to 15 degrees Celsius higher (ambient temp is 24, GC shows 38). In my opinion it doesnt make sense to show it, if there is no way to calibrate.

**Comment by Gissio** [comment]
Agreed. Next beta will replace device temperature with device battery voltage (which makes more sense).

**Comment by Gissio** [comment]
I just released beta21 which fixes this.

https://github.com/Gissio/radpro/releases

**Comment by martin-machacek** [comment]
Unfortunately it turns on and the screen is blank (probably the background color, does not seem to be white). I can hear particle clicks and particle LED flashes, but nothing else. Key presses don't help.

**Comment by Gissio** [comment]
My bad. Try beta22 now!

**Comment by martin-machacek** [comment]
beta22 works and shows the battery voltage. 
4.539V connected to USB, after disconnecting it slowly settles for cca 10 minutes down to 3.780 and than slower as it discharges.

**Comment by Gissio** [comment]
Nice!

**Comment by Gissio** [comment]
Can I make a request? It would be great if you can measure the discharge curve of the battery so the battery indicator shows a correct value.

This would imply fully charging the device, and taking note of the voltage value every 10 minutes. It would be great if you do this with the screen off. Can you do this?

**Comment by martin-machacek** [comment]
I can try tomorrow. I am thinking of ways to automate this. Wouldn't it be possible to log it internally?

**Comment by Gissio** [comment]
It would be, but I think it takes less time to do this manually than for me to program the code.

**Comment by martin-machacek** [comment]
Ok, I will give it a try tomorrow then

**Comment by Tig3rch3n** [comment]
I can test both of my devices with the power profiler in a few days.
I even plan to do different Setups

Brightness max/Display on all the Time vs Brighness min/Sleep after 30sec and a few in between

**Comment by Gissio** [comment]
A measurement on one device should be enough. 

Use only brightness max/display on all time so the measurement takes less time.

Thanks in advance!

**Comment by Tig3rch3n** [comment]
Btw... would it be possible to enable a Temp Offset?
I have a big'ish diff in both directions

Roomtemp 23°
Device 1 14°
Device 2 27.5°

**Comment by martin-machacek** [comment]
Temp offset setting would be nice.

I am still collecting the voltage values. The battery lasted whole day yesterday and still has 3.533V. After having it switched off for the night I have charged it up for 30s and when the voltage dropped back to the last value from yesterday, I have resumed logging.

**Comment by Tig3rch3n** [comment]
Same, i did a Sleep after 30s run yesterday and do a always on min brightness at the moment :)

**Comment by martin-machacek** [comment]
Here is my voltage log: [Fnirsi-GC-01-voltage-log.txt](https://github.com/Gissio/radpro/files/14636246/Fnirsi-GC-01-voltage-log.txt)
The device turned off after the last value of 3.042V
Parameters during test:

- Interval 10 minutes
- Display sleep after 30 seconds
- Display brightness level High 
- Rad Pro version 2.0beta22

**Comment by Gissio** [comment]
They say an image is worth a thousand words.

![fnirsi-gc01-battery-discharge](https://github.com/Gissio/radpro/assets/119644301/5f2b5f0b-2367-452b-b7a1-50aeff097b38)

Thanks for all the hard work!

**Comment by Gissio** [comment]
Updated curve is available in 2.0rc01!
