### ISSUE TITLE
Different FS2011: GD32F103

### ISSUE THREAD

**Issue by felixsteghofer** [Gissio/radpro#3]
Hi,
I received a FS2011 from aliexpress and the board revision seems to be slightly different (e.g. buzzer, tube location + some components), plus the cpu is different
GD32F103
C8T6
CDU1310
DJ2216
GigaDevice
ARM

After programming, no display, no sounds, buttons don't seem to do anything. After flashing the backup two or three times it is working again.
![front](https://github.com/Gissio/radpro/assets/1248692/0051927d-3a55-4155-bf39-f9b0ff95c746)

![back](https://github.com/Gissio/radpro/assets/1248692/0c050fd6-9bb5-4e24-8854-a7ee68b54354)

![cpu](https://github.com/Gissio/radpro/assets/1248692/3a776024-7558-4ed9-b518-9e4e4fab2f19)

![cpu_2](https://github.com/Gissio/radpro/assets/1248692/716ac431-5e45-4095-8eaa-524cc9d3acc5)

Not really experienced with ARM CPUs so some hints on where/how I can find the correct board definitions would be very beneficial, otherwise I will try on my own, probably in the next days.

(tried to flash some of the later versions but none seems to work)

**Comment by Gissio** [comment]
Interesting. Please go to this project's Security Tab, draft a new security advisory, and send me your email address so I can contact you. Your email address won't be released publicly.

**Comment by Gissio** [comment]
Fixed in the upcoming release (1.4.0)!

**Comment by Gissio** [comment]
Rad Pro 2.0 Beta 11 is out!

https://github.com/Gissio/radpro/releases
