### ISSUE TITLE
FNIRSI GC-01: Charge icon while on batteries

### ISSUE THREAD

**Issue by mileshkin** [Gissio/radpro#37]
Battery icon stays the same not depending the battary charge percent or charging process.
It shows fully gray battery with gray flash icon on it.

**Comment by Gissio** [comment]
Go to the statistics menu. What's the battery voltage?

**Comment by mileshkin** [comment]
It's 3.85 V

**Comment by Gissio** [comment]
Strange, everything seems nominal.

Can you attach a picture of the statistics screen?

**Comment by mileshkin** [comment]
![photo_2024-03-22_20-27-31](https://github.com/Gissio/radpro/assets/15636339/9e98b1e2-6bad-40aa-ad79-f0ceb65dea42)

**Comment by Gissio** [comment]
You didn't mention the flash symbol!

It seems the GC-01 thinks it's charging, while it's not. I'll report once I have news.

**Comment by martin-machacek** [comment]
He did:
> Battery icon stays the same not depending the battary charge percent or charging process. It shows fully gray battery **with gray flash icon on it**.

I have encountered this issue, too.

**Comment by mileshkin** [comment]
> You didn't mention the lighting symbol!
" with gray flash icon on it " was exactly about it... may be my bad english caused you missunderstood me

**Comment by Gissio** [comment]
I'm sorry, it seems the cold I'm going through is worse than I thought.

**Comment by Gissio** [comment]
Can you try 2.0rc2?

**Comment by mileshkin** [comment]
> Can you try 2.0rc2?

lighting symbol gone... at least. Battery is fully charged for now and the indicator shows full battery.

**Comment by Gissio** [comment]
Unfortunately the GC-01 hardware signals "charging" when it is not plugged to USB. So there is no easy way to distinguish from: "unplugged", "charging on USB", and "plugged-in to USB with batteries charged".
