### ISSUE TITLE
Random Number Generator question

### ISSUE THREAD

**Issue by pixitha** [Gissio/radpro#4]
The docs: https://github.com/Gissio/radpro/blob/main/docs/manual.md#random-number-generator talk about using a radioactive source to speed things up, but it doesn't list any suggested length of time it should take under normal background radiation. Can you clarify what we would expect to see?

I ran the random password with full ASCII for quite a while and never saw any output?

**Comment by Gissio** [comment]
It actually says "The random number generator produces one bit for every two new pulses". Thus you need two pulses for every RNG bit.

Try "Coin Flip". You should get one bit for every two pulses. If you don't, there is probably some GD32-related bug. Please report.
