### ISSUE TITLE
Ok Guys, here is the foolproff to get the FW loaded. Works everytime.....

### ISSUE THREAD

**Issue by jackhen** [Gissio/radpro#43]
Ok Guys, here is the foolproff to get the FW loaded. Works everytime.....
After you connect your GC-01 via usb to your PC you "hold down" the power switch. As long as you hold it down, you will see the disk appear on your PC. So hold it down, then drag the repo onto your disk icon. Release the power button when you see the GC-01 booting. Takes only a few seconds. And it doesn't matter the USB protocol. It just works.

_Originally posted by @jackhen in https://github.com/Gissio/radpro/discussions/24#discussioncomment-8890588_

**Comment by Gissio** [comment]
Added to the installation instructions. Thanks for the report.

**Comment by jackhen** [comment]
Gassio,
You can go to
https://www.youtube.com/watch?v=23sX-_Oo_h0&lc=UgzLD925mnA5s3N0Fzp4AaABAg.A1Lv1ezGxPDA1MFH59vPFe
and see this guy and what he shows based on your FW. You can also see his
technique to load your FW.
