### ISSUE TITLE
BR-6: Support

### ISSUE THREAD

**Issue by StrandedAlien** [Gissio/radpro#53]
![image](https://github.com/Gissio/radpro/assets/89656885/0f4d81a7-190e-41a1-8b09-aa5b9a245bc6)

There is a teardown on YT showing the same PCB just with a graphics display. https://www.youtube.com/watch?v=fNMOmk37HbM. Looks to me like another display, but the rest might be standard. Any chance?

**Comment by Gissio** [comment]
I have never worked with the STC8A8K64D4 MCU so I can't support it.

Let me refer you to this answer: https://github.com/Gissio/radpro/issues/5#issuecomment-1666939961

**Comment by Gissio** [comment]
I have never worked with the STC8A8K64D4 MCU so I can't support it.

But I can give you some hints as to what would need to be done (general hints, not support):

* Follow the traces from the microprocessor to the board's devices (keyboard, display, battery, etc) and see what port connects to what device. A multimeter might help.
* The 4-pin header is an SWD connector. Get a STLINK dongle, and attempt to download the firmware through it. Then use some disassembly tool to disassemble the firmware, and see how the code accesses the MCU internal devices (input/output ports, timers, ADCs, etc).
* Then, follow the steps in https://github.com/Gissio/radpro/blob/main/docs/developers.md and customize the code for the BR-6.

This should make a nice project...

**Comment by StrandedAlien** [comment]
Thanks for the hints and the fast answer . I don't know this MCU neither and I a do only occasionally Arduino programs. Too bad. Nice device though. I have better chances to find the tube tick signal and add an Esp32 and write from scratch.Am 02.04.24, 02:20 schrieb Gissio ***@***.***>:

   
  I have never worked with the STC8A8K64D4 MCU so I can't support it. 
  But I can give you some hints as to what would need to be done (general hints, not support): 
   
   Follow the traces from the microprocessor to the board's devices (keyboard, display, battery, etc) and see what port connects to what device. A multimeter might help. 
   The 4-pin header is an SWD connector. Get a STLINK dongle, and attempt to download the firmware through it. Then use some disassembly tool to disassemble the firmware, and see how the code accesses the MCU internal devices (input/output ports, timers, ADCs, etc). 
   Then, follow the steps in https://github.com/Gissio/radpro/blob/main/docs/developers.md and customize the code for the BR-6. 
   
  This should make a nice project...
