### ISSUE TITLE
FNIRSI GC-01: Recovery

### ISSUE THREAD

**Issue by Red-Owl** [Gissio/radpro#57]
i have rewrite a cpu firmware ad have used https://www.amazon.it/dp/B07H9XV2W2/ to upload firmware in jtag, check wire connection from to gg-01, the cpu is ch32f103r8 che st v2 read the cpu, and succefull write, the display remain blank

i use a stm32 official software in windows to write a cpu.

**Comment by Gissio** [comment]
Attendi un paio di giorni, pubblicherò istruzioni per ripristinare il GC-01 con un dongle STLINK!

**Comment by Red-Owl** [comment]
io aspetto :)

**Comment by Gissio** [comment]
Ecco le istruzioni per il flashing dell'FNIRSI GC-01 con un STLINK: https://github.com/Gissio/radpro/blob/main/docs/devices/FNIRSI%20GC-01/install-stlink.md

**Comment by Red-Owl** [comment]
Upload facilissimo, 
veramente ottimo fa tutto da solo.


![IMG_20240421_154639354](https://github.com/Gissio/radpro/assets/36891854/97e3067a-9d18-4074-8512-f5299207c513)
![IMG_20240421_154559046](https://github.com/Gissio/radpro/assets/36891854/e216eb3d-7922-4b6a-b5c9-7977b1d42369)
![IMG_20240421_154548180](https://github.com/Gissio/radpro/assets/36891854/79b29e45-28be-4cc5-ad2c-146350efa060)

che comando devo usare per leggere i dati di continuo dal pc ?
posso chiederti se puoi mettere i comandi in json tipo:

[{"cmd":"getdeviceId"}]
...
[{"staus":"OK","model":"FNIRSI GC-01 (CH32F103C8)","sw":"Rad Pro 2.0rc3;8869569e"}]

dato che lo leggo da javascript basta fare un **eval o json parse** e restutuisce un array facilmente utilizzabile
....
(nodejs su nw.js)

**Comment by Gissio** [comment]
Eccellente!

Leggi https://github.com/Gissio/radpro/blob/main/docs/comm.md .
