### ISSUE TITLE
Bosean FS-1000 support

### ISSUE THREAD

**Issue by murkle** [Gissio/radpro#6]
Hi, this looks very cool!

For the FS1000 do you think the direct logging to the computer would work with the built in USB socket?

**Comment by mressl-itba** [comment]
Hi there!

Could you attach photos of the electronics board? (If possible, right from above, without light reflections)

Also, could you go to the "Security" tab and report a vulnerability with your email address so I can contact you in private? Your email address won't be published.

**Comment by murkle** [comment]
I'm michael at geogebra.org

I don't have a device (yet 😆)

I'm interested in connecting via eg WebSerial or WebHID, will that be possible? I can code the JavaScript side

**Comment by mressl-itba** [comment]
First, let me take my hat off for your work at geogebra.org.

I don't own a Bosean FS1000 either, so I can't confirm whether the factory firmware supports live data logging. But, if you are willing to help, it shouldn't be too hard to adapt Rad Pro for the FS1000.

**Comment by murkle** [comment]
Thanks!

Shall we take this to email?

**Comment by Gissio** [comment]
Rad Pro 2.0 Beta 11 is out!

https://github.com/Gissio/radpro/releases

**Comment by Gissio** [comment]
Rad Pro 2.0 Beta 14 is out!

https://github.com/Gissio/radpro/releases
