### ISSUE TITLE
FNIRSI GC-01: Schematics error

### ISSUE THREAD

**Issue by Red-Owl** [Gissio/radpro#62]
quando hai reversato lo schema, a mio parere, il duplicatore di tensione e' sbagliato
il duplicatore dovrebbe avere i consensatori in serie e i diodi che vanno da  +/- 
https://www.lucianomarroccu.com/un-p%C3%B2-di-teoria/moltiplicatore-di-tensione/
il primo che ho trovato

p.s.
stavo pensando ma se con il https://www.google.com/search?q=esp32+WT32-SC01, gli facessi un geiger con il tuo software
avremmo usb dati, sd, wifi webserver o bluetooth, 
(costa meno un geiger gia fatto del solo tubo)

**Comment by Gissio** [comment]
Automatic translation for the convenience of other readers:

> "when you reversed the diagram, in my opinion, the voltage doubler is wrong. The doubler should have capacitors in series and diodes ranging from +/- https://www.lucianomarroccu.com/un-p%C3%B2-di-teoria/multiplicatore-di-tensione/ the first one I found

The schematics was donated by a well-intentioned and very capable person. It simplified development of Rad Pro substantially. Other than that, I just published it in the repository (with permission) for reference.

> p.s. I was thinking but what if with the https://www.google.com/search?q=esp32+WT32-SC01, you gave it a geiger with your software we would have data usb, sd, wifi webserver or bluetooth, (an already made geiger costs less than just the tube)"

Sounds like a nice project!
