### ISSUE TITLE
FNIRSI GC-01: Doc improvements

### ISSUE THREAD

**Issue by Elfe12** [Gissio/radpro#68]
Errors in description of GD-01 Flashtool:

1. The pins in my GD-01 (CH32F103) from left to right, are: 
SWCLK
SWDIO
GND
+3.3V
Maybe the order changes from release to release :)
But it is written on the board, that's why its no problem for me.

2. Please write in description, that the ST-link dongle **and** the power USB has to be connected for a successful flashing.
3. Thanks for this great project

**Comment by Gissio** [comment]
Thanks for your comments!

It is good to know there are different hardware versions. Will update description soon.

In many implementations, the +3.3V SWD pin is connected directly to the CPU. That does not seem the case with your device. Will update as well.

Thanks for thanking. It is not many people who say thanks, so a double thanks to you.
