### ISSUE TITLE
Firmware boot halted

### ISSUE THREAD

**Issue by PsychoBitchy** [Gissio/radpro#73]
Hello.
No matter what I try on my FINRSI CH32F
- Downloading and uploading 2.0rc3 or 2.0rc4 built firmware from repo.
- Building from source / signing, from the last repo version.
- 2.0rc2 is stable on my device and doesn't cause hang.
- All 2.0 versions loose date/time/hour on switching off

The device boots up just after the flash and is running fine, but if I switch the device off then on again multiple time, *at some point* ( there is no pattern that I could determine ) the device stays stucked on "Radpro version" screen then blacks out. In that state, not even the power button works. It's in hanged state.

**Edit: The device eventually goes back to life, but after a solid 30 seconds or so.
I had the impression it was stucked because at some point the boot process is much longer.**

I have to reset then reflash to bring it back to life.

Never had a glitch with the stock firmware.

Any ideas?

![output_9](https://github.com/Gissio/radpro/assets/17138173/11bd77c1-86ed-4309-8f1f-ba95c675e920)

**Comment by PsychoBitchy** [comment]
**Edit: The device eventually goes back to life, but after a solid 30 seconds or so.
I had the impression it was stucked because at some point the boot process is much longer.**
Not a bug, closing

**Comment by Gissio** [comment]
Most likely your CR1220 battery needs replacement!

I've added your questions in the [Q&A section of the user manual](https://github.com/Gissio/radpro/blob/main/docs/users.md#faq).

**Comment by Gissio** [comment]
It's not actually hung, it's Rad Pro waiting for the microprocessor to start the real-time clock. The CH32 takes quite a while to do that.

Once you replace the battery, it should start right away.

**Comment by PsychoBitchy** [comment]
Hello, just a small update on this case:
Replacing the board backup CR1220 battery indeed fixed every issues I had.
Thanks for pointing out and eagle-eye spotting the issue here.
