### ISSUE TITLE
Rad Pro: 12-hour time format error

### ISSUE THREAD

**Issue by oOblik** [Gissio/radpro#75]
https://github.com/Gissio/radpro/blob/e57e4c57872989e01ccd306a02a22a6d0d17a5a5/platform.io/src/display.c#L949

Something like this instead?

`strcatUInt32(buffer, (dateTime.hour % 12) ? (dateTime.hour % 12) : 12, 1);`

**Comment by Gissio** [comment]
Fixed.

Thanks for the contribution!
