### ISSUE TITLE
FS2011 (GD32F150C8) self compiled 2.0rc5: installed vibration motor on Q5: power up vibration starts weak.

### ISSUE THREAD

**Issue by Dsl71** [Gissio/radpro#78]
Setup: Haptic Pulses -> strong

After power on for the first pulses the motor runs weak. (half turn or so).
Later on, with more pulses it runs normal.

This behaviour is not always, after a short power off->power on cycle it runs normal from power on.

![Vibrationsmotor](https://github.com/Gissio/radpro/assets/57271038/d969b92e-b2e8-43e3-b14b-234b681be71b)

**Comment by Gissio** [comment]
I can't support custom mods.

Suggestion: use an oscilloscope.
