### ISSUE TITLE
FNIRSI GC-01: Graph bar display not accurate  

### ISSUE THREAD

**Issue by gkulka-web** [Gissio/radpro#79]
I've noticed that graph bar is not correctly displaying actual reading. Reading is 0,121uS/h while graph is almost at 0,5uS/h
![IMG_20240521_202953](https://github.com/Gissio/radpro/assets/60449320/4a7f86ba-5807-4641-aca8-4eb2ca066406)

**Comment by Gissio** [comment]
The bar graph is [logarithmic](https://en.wikipedia.org/wiki/Logarithm): the first tick represents 0.01 µSv, the second one, 0.1 µSv, the third, 1 µSv, and so on.
