### ISSUE TITLE
GC-01 Has an entirely different board

### ISSUE THREAD

**Issue by mcalexer** [Gissio/radpro#93]
Hello all,

Never posted anything on Github before, so if I say something wrong let me know.

Just got a Fnirsi GC-01 in the mail a few days ago and was excited to get Radpro on it, unfortunately while reading the instructions, it seems like they have put out a total board revision. It is completely different, and even the piezo speaker is no longer on the back of the board.

To make things worse, the MCU is completely blank, they sanded off the identifying markings. Really blows, if I knew they did this, I never would have bought it.

Is there a certain MCU I should assume it has?

![20240604_185730](https://github.com/Gissio/radpro/assets/146769348/7b3a1f39-8416-40ee-bfb2-d2303f5b21ea)
![20240604_185744](https://github.com/Gissio/radpro/assets/146769348/d1136d60-94e5-41c8-a281-b9d53eed16c1)

**Comment by ReimuHakurei** [comment]
That's probably one of the counterfeit GC-01s and not a real one.

**Comment by Gissio** [comment]
The board looks very similar to #48. Closing due to duplicate issue.

**Comment by Gissio** [comment]
The board looks very similar to #48. I'd suggest returning it and get a refund.

Closing due to duplicate issue.
