### ISSUE TITLE
FNIRSI GC-01: What triggers the "Beep" and "Burp"?

### ISSUE THREAD

**Issue by ullix** [Gissio/radpro#95]
When I run the counter with e.g. too low an anode voltage, there will be - but only after a while - a loud beep and a loud burp (aka vibration). Obviously some warning message; I don't see a menu entry to switch this on/off.

What does trigger this warning, is it hardware or RadPro firmware related, and what is its meaning?

**Comment by Gissio** [comment]
Please read the fault section of the manual: https://github.com/Gissio/radpro/blob/main/docs/users.md
